workout-logger:
    environment:
        SPRING_PROFILES_ACTIVE: mongo
        STORE_MONGO_HOST: MONGO
    image: weizilla/workout-logger
    ports:
        - "80:80"
    links:
        - mongo
mongo:
    image: mongo
