workout-logger:
    environment:
        SPRING_PROFILES_ACTIVE: mongo
        SPRING_DATA_MONGODB_URI: mongodb://MONGO/workouts
    image: weizilla/workout-logger
    ports:
        - "80:80"
    links:
        - mongo
mongo:
    image: mongo
